name: Warm Up Serverless Function

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Serverless Function
        run: curl -s https://sod-bot.vercel.app/api/slackEvents
